### ISSUE TITLE
improve typing

### ISSUE THREAD

**Issue by mengwong** [smucclaw/baby-l4#30]
are we reinventing typescript?

**Comment by anka-213** [comment]
What was the actual goal of this issue? I don't remember the context.

**Comment by mengwong** [comment]
consider error types that we can steal from Text.Megaparsec.Error, and maybe elm

the actual goal of this issue was to basically add type checking to the language. We aren't doing HM type inferencing to start, just basic type checking from `class … { attribute : type }` definitions.

We want to send back useful error messages so the IDE can display the source of type errors. @
