### ISSUE TITLE
Fix installation instructions to make GF_LIB_PATH permanent

### ISSUE THREAD

**Issue by anka-213** [smucclaw/baby-l4#39]
See discussion here: https://smucclaw.slack.com/archives/C0164JRERL0/p1616728533003400?thread_ts=1616728235.001000&cid=C0164JRERL0

```
echo 'export GF_LIB_PATH=something' >> ~/.zshrc
```
or something like this should work (assuming zsh).

We should also add instructions for doing the
```
stack install
```
and adding `~/.local/bin` to `PATH` so the IDE can find it.

**Comment by inariksit** [comment]
Redundant, see #93
