### ISSUE TITLE
Add support for proper command line parsing, as in the main dsl repo

### ISSUE THREAD

**Issue by anka-213** [smucclaw/baby-l4#6]
Basically what this pr did: https://github.com/smucclaw/dsl/pull/27

**Comment by anka-213** [comment]
We could also merge the lsp server into the main and have a flag for running it as lsp.

**Comment by alfredats** [comment]
I can jump on this if nobody's working on it.

**Comment by anka-213** [comment]
@alfredats  Yes please. Thanks!
