### ISSUE TITLE
Show type information on hover

### ISSUE THREAD

**Issue by kharus** [smucclaw/baby-l4#65]
https://github.com/smucclaw/baby-l4/blob/247752a5db143ae05bb60bbafc34d7d104921e95/lsp/Main.hs#L214-L214

**Comment by anka-213** [comment]
Same structure as with parsing + hover:

1. Run the parser as before (showing errors if it fails)
2. Run type checker (see `src/Main.hs` for an example)
3. If there were type errors, display them as diagnostics
4. If no type errors, extract the type information from the `annotation` field of the AST nodes.
