### ISSUE TITLE
Handle different kinds of problems differently!

### ISSUE THREAD

**Issue by kharus** [smucclaw/baby-l4#67]
https://github.com/smucclaw/baby-l4/blob/247752a5db143ae05bb60bbafc34d7d104921e95/lsp/Main.hs#L210-L212

This function should be replaced with one that allows us to capture different types of errors. Later, where we handle these errors, we need to handle them in different ways, including:
- Just ignoring some minor issues and just not displaying any hover information
- Showing diagnostic information when we have a location for the issues (and making sure that the diagnostics are preserved as long as they should)
- Showing a different kind of error, e.g. a pop-up-box for more serious errors and bugs that doesn't have a relevant location.

**Comment by anka-213** [comment]
This issue depends on #66

**Comment by anka-213** [comment]
Example of how to send messages: https://github.com/haskell/lsp/blob/master/lsp/example/Reactor.hs#L179
